### PR TITLE
Added nomenclature table, fixes #2

### LINKED ISSUE #2: Add nomenclature table
Provide an alphabetically sorted nomenclature table with symbols, units and abbreviations (see author’s guide).

### PR DESCRIPTION
**Pull request by mjseabright**
I hope this is what they were after. I added every symbol, unit and abbreviation I could find.

### CODE REVIEW

**Comment by mjseabright** [comment]
Actually, I'm an idiot. I reread the authors guide (https://www.elsevier.com/journals/biosystems-engineering/1537-5110/guide-for-authors) and it doesn't say to define units, it says to define symbols, with units. I'll fix it. I hate writing papers, also I hate my stupidity...

**Comment by markhedleyjones** [comment]
@mjseabright, I made come changes to the nomenclature table. Please take a look and let me know what you think.

**Comment by markhedleyjones** [comment]
Ah, I've just read your comment about not defining units. Well, that's exactly what I did too. Removed.

**Comment by mjseabright** [comment]
Nice work.

**Pull request merged**
