### PR TITLE
Added qualitative and fixed hierarchy. Fixes #6

### LINKED ISSUE #6: Change title of Sections 4.0.1 to 4.0.3
Sections 4.0.1 to 4.0.3 report qualitative evaluations of sensors, as there was no experimental design and no data analyses. So, change each title to “… qualitative evaluation”.

### PR DESCRIPTION
**Pull request by mjseabright**
Added the word 'Qualitative' to section titles.

Also moved them up in the hierarchy by one level as it didn't make sense the way it was (there was a 4.0.1 without a 4.1).

### CODE REVIEW

**Comment by markhedleyjones** [comment]
Cool, I like hierarchy change but I'm not sure about the addition of the work "qualitative". It should be added somewhere... Hmm....
* In-orchard Camera Qualitative Evaluation
* Qualitative In-orchard Camera Evaluation
* Qualitative Camera Evaluation

Or, since it has been added to every sub-section, what do you think about changing the title of the whole section:
* Navigation Sensor Selection
* Qualitative Navigation Sensor Evaluation
* Qualitative Sensor Evaluation
* Navigation Sensor Selection (Qualitative)

**Comment by mjseabright** [comment]
Yea, reading it again, I agree. I think changing the section title, so something like this:

- 4\. Qualitative Navigation Sensor Evaluation
  - 4.1 Camera
  - 4.2 Lidar
  - 4.3 GNSS

Thoughts?

**Comment by markhedleyjones** [comment]
Yep, I like it. :+1:

**Comment by mjseabright** [comment]
Awesome. Done. Merge if you're happy.

**Pull request merged**
